### ISSUE TITLE
Broken _config.yml

### ISSUE THREAD

**Issue by hxxbit** [SerraraFluttershy/serrarafluttershy.github.io#1]
It seems as though the site is looking for resources under a folder that doesn't exist.

How to replicate:
Open site

Expected: Site has corrected styling. 

Occurence: Site is broken.

Thanks in advanced.

**Comment by hxxbit** [comment]
I've just fixed the issue and created a pull request.. paging maintainer @SerraraFluttershy

**Comment by hxxbit** [comment]
Oops! Accidentally closed it. Sorry.

**Comment by SerraraFluttershy** [comment]
fixed
